# -------------------- Logging --------------------
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO

# -------------------- MongoDB --------------------
spring.data.mongodb.uri=mongodb://localhost:27017/paymentDB

# -------------------- PostgreSQL --------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/paymentdb
spring.datasource.username=postgres
spring.datasource.password=Kaiko1994Ulia

# -------------------- Kafka --------------------
# docker-compose -f docker-compose-kafka-only.yml up
spring.kafka.bootstrap-servers=localhost:9092

# Max time to wait for a response from Kafka broker before failing the request
spring.kafka.properties.request.timeout.ms=30000

# Limited retries to fail fast in dev
spring.kafka.properties.retries=3

# Time before consumer is considered dead (faster fail in dev)
spring.kafka.consumer.properties.session.timeout.ms=10000

# How often consumer sends heartbeat (faster detection in dev)
spring.kafka.consumer.properties.heartbeat.interval.ms=3000

# Time to wait between retry attempts when a Kafka request fails
spring.kafka.properties.retry.backoff.ms=1000

# -------------------- Kafka Admin --------------------
spring.kafka.admin.properties.request.timeout.ms=30000
spring.kafka.admin.fail-fast=false
