# -------------------- Logging --------------------
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO

# -------------------- MongoDB --------------------
spring.data.mongodb.uri=mongodb://localhost:27017/paymentDB

# -------------------- PostgreSQL --------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/paymentdb
spring.datasource.username=postgres
spring.datasource.password=Kaiko1994Ulia

# -------------------- Kafka --------------------
# docker-compose -f docker-compose-kafka-only.yml up
spring.kafka.bootstrap-servers=localhost:9092

# Limited retries to fail fast in dev
spring.kafka.properties.retries=3

# Time before consumer is considered dead (faster fail in dev)
spring.kafka.consumer.properties.session.timeout.ms=10000
